### ISSUE TITLE
Request for cmake settings used to compile the binaries

### ISSUE THREAD

**Issue by MitchellSingleton** [Mootikins/FreeplayILI9341#3]
Hello Mootikins,
I have swapped out my CM3+ for a CM4S and am unable to use your binaries without underclocking by setting my speed to 400 to match the CM3 speed.
Could you please provide your cmake parameters so that I can change the -DSPI_BUS_CLOCK_DIVISOR to 8 and build the binaries?
Thank you,
Mitchell

**Comment by Mootikins** [comment]
It’s been a _long_ time since I did any work on this, but the binaries were compiled from https://github.com/juj/fbcp-ili9341 — there specifically are some sections in the README explaining the CMake parameters. I _know_ you will need the `SPI_BUS_CLOCK_DIVISOR`, `FREEPLAYTECH_WAVESHARE32B`, `ARMV8A`, and potentially some from the “other build options” section.

I also saw [this](https://github.com/juj/fbcp-ili9341?tab=readme-ov-file#specifying-display-speed) —- does that not cover your needs, or is that what you were referencing above?

I also do not remember what values were used for the crop/offset on the display, so you may need to fiddle around with those. In hindsight, I should have set this up to compile the latest (or use CI to build new releases which are then fetched).

**Comment by MitchellSingleton** [comment]
Thank you, I was hoping that you had notes or something on the builds.

I think that i was able to fix the issue that I was having and have replicated the full screen binary. i really wanted to use full screen, however my initial build didn’t fill the full screen.

This comment pointed me towards the code to change: https://forum.freeplaytech.com/showthread.php?tid=4931&pid=8610#pid8610

> In `freeplaytech_waveshare32b.h`: (also important as unmodified juj driver have not access to Freeplay screen config)
> `DISPLAY_NATIVE_COVERED_TOP_SIDE` is left border of the screen
> `DISPLAY_NATIVE_COVERED_LEFT_SIDE` is top border of the screen
> `DISPLAY_NATIVE_COVERED_RIGHT_SIDE` is bottom border of the screen
> `DISPLAY_NATIVE_COVERED_BOTTOM_SIDE` is right border of the screen

By setting the values to 0, I now have a full screen binary that works and no longer have to underclock the Pi4.

**Comment by MitchellSingleton** [comment]
this text and the link to the post explains what your no sleep binaries turned on/off:

“edit '/home/pi/Freeplay/fbcp-ili9341/config.h':
Comment mean add // at beginning of the line, to uncomment, remove it.

ALL_TASKS_SHOULD_DMA //to uncomment, as Mootikins pointed out, the one not really needed
SAVE_BATTERY_BY_PREDICTING_FRAME_ARRIVAL_TIMES //to comment, framerate drop fix
DISPLAY_FLIP_ORIENTATION_IN_SOFTWARE //to comment, I don't remember why
SAVE_BATTERY_BY_SLEEPING_WHEN_IDLE //to comment, good catch kmacmart@darkcloud.ca”

https://forum.freeplaytech.com/showthread.php?tid=4989

**Comment by MitchellSingleton** [comment]
Thank you for the work you put into this. I just found your post to do pretty much what i was asking: “[GUIDE] Building Experimental Display Driver with Custom Settings”

https://forum.freeplaytech.com/showthread.php?tid=5009
